version: 2
updates:
  - package-ecosystem: "gradle"
    directory:
      - "/"
      - "linear-checker-qual-android/"
      - "linear-checker-qual"
    schedule:
      interval: "daily"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
